# Worktree Configuration Rules

# Worktree Management
Worktree_Rules: |
  - All worktrees for this project MUST be created in the worktrees/ folder
  - Use descriptive names that indicate the feature or purpose
  - Clean up old worktrees when no longer needed
  - Coordinate with team members to avoid naming conflicts
  - Example: git worktree add worktrees/feature-name origin/feature-branch

# Directory Structure
Worktree_Structure: |
  - worktrees/
    - feature-branch-name/
    - bugfix-issue-123/
    - experiment-new-feature/
  - Each worktree should be self-contained for its specific purpose
  - Avoid creating worktrees outside the worktrees/ directory

# Best Practices
Worktree_Best_Practices: |
  - Create worktrees for feature development, bug fixes, and experiments
  - Keep main branch clean and stable
  - Use worktrees to maintain multiple active development streams
  - Remove worktrees after merging or abandoning features
  - Use git worktree prune to clean up orphaned worktree references