# OAuth Configuration & Security Guidelines

OAuthSecretManagement:
  critical_note: "OAuth failures are often due to missing or misconfigured secrets in Cloudflare Workers"
  
  required_secrets:
    - "GOOGLE_CLIENT_ID: From Google Cloud Console"
    - "GOOGLE_CLIENT_SECRET: From Google Cloud Console"
    - "GOOGLE_REDIRECT_URI: MUST match Google Console exactly"
    - "JWT_SECRET: For OAuth state token signing"

  verification_command: "wrangler secret list"

OAuthFailurePatterns:
  oauth_configuration_error: "Missing GOOGLE_REDIRECT_URI secret"
  hmac_key_length_zero: "Missing or empty JWT_SECRET"
  invalid_client: "GOOGLE_CLIENT_ID/SECRET mismatch"
  redirect_uri_mismatch: "Google Console ≠ GOOGLE_REDIRECT_URI secret"

OAuthSecretCommands:
  check_secrets: "wrangler secret list"
  production_secrets:
    - "wrangler secret put GOOGLE_CLIENT_ID"
    - "wrangler secret put GOOGLE_CLIENT_SECRET"
    - "wrangler secret put GOOGLE_REDIRECT_URI"
    - "wrangler secret put JWT_SECRET"
  verify_deployment: "wrangler deploy"

OAuthRedirectURI:
  production: "https://emilycogsdill.com/api/auth/google/callback"
  critical_requirement: "MUST match Google Cloud Console → APIs & Services → Credentials"
  warning: "Both places must be identical or OAuth will fail"

OAuthTroubleshootingWorkflow:
  steps:
    1: "Check 'wrangler secret list' - verify all 4 secrets exist"
    2: "Verify Google Cloud Console redirect URI matches exactly"
    3: "Check Worker is deployed: 'wrangler deploy'"
    4: "Test OAuth flow in production environment"
    5: "Monitor logs for specific error patterns"