ProjectIdentity: &ProjectIdentity
  name: "baba-is-win"
  repository: "baba-is-win"
  description: "Personal website and blog built with Astro, featuring blog posts, thoughts, museum portfolio, and authentication system"
  technology_stack:
    framework: "Astro"
    language: "TypeScript"
    database: "SQLite/D1"
    runtime: "Cloudflare Workers"
    testing: "Vitest/Jest"
    styling: "CSS"
  naming_conventions:
    github_repository: "baba-is-win"
    cloudflare_resources: "baba-*"
    database: "baba-db"

ProjectStructure: &ProjectStructure
  architecture: "Static site with dynamic auth features on Cloudflare Workers"
  key_directories:
    src/components: "Astro components and Svelte components"
    src/pages: "Astro pages and API routes"
    src/lib: "Authentication, OAuth, and utility libraries"
    src/data: "Blog posts, thoughts, and content data"
    public/assets: "Static assets including images and fonts"
    migrations: "Database schema migrations"
    worktrees: "Feature branch worktrees"
  deployment_targets:
    production: "Cloudflare Pages"
    database: "Cloudflare D1"

DevelopmentCommands: &DevelopmentCommands
  development:
    local_dev: "npm run dev"
    build: "npm run build"
    preview: "npm run preview"
    database_setup: "bash scripts/setup-db.sh"
  testing:
    unit_tests: "npm test"
    coverage: "npm run test:coverage"
    oauth_tests: "npm run test:oauth"
  deployment:
    build_check: "npm run build"
    deploy: "Deploy via Cloudflare Pages integration"