name: Debug Content Items

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check content items state
        run: |
          echo "=== CONTENT ITEMS DEBUG ==="
          curl -X GET https://personal.emily-cogsdill.workers.dev/api/admin/debug-content \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -s | jq '.'
      
      - name: Run reset notifications
        run: |
          echo ""
          echo "=== RUNNING RESET ==="
          curl -X POST https://personal.emily-cogsdill.workers.dev/api/admin/reset-notifications \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{"resetContent": true, "resetNotifications": true}' \
            -s | jq '.'
      
      - name: Check content items after reset
        run: |
          echo ""
          echo "=== CONTENT ITEMS AFTER RESET ==="
          curl -X GET https://personal.emily-cogsdill.workers.dev/api/admin/debug-content \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -s | jq '.summary'