name: Wait and Notify Subscribers

on:
  push:
    branches: [main]
    paths:
      - 'src/data/blog-posts/published/**'
      - 'src/data/thoughts/published/**'

jobs:
  wait-and-notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Wait for Cloudflare auto-deployment
        run: |
          echo "🚀 Content changes detected - waiting for Cloudflare to auto-deploy..."
          echo "⏱️  Waiting 2 minutes for deployment to complete..."
          sleep 120
        
      - name: Trigger email notifications
        run: |
          echo "📧 Triggering email notifications..."
          curl -X POST "${{ secrets.SITE_URL }}/api/admin/trigger-content-sync" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            --fail --silent --show-error
          echo "✅ Email notification trigger completed"