name: Process Email Notifications

on:
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check for pending notifications
        id: get-pending
        run: |
          response=$(curl -X GET https://personal.emily-cogsdill.workers.dev/api/cron/get-pending-notifications \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -f)
          
          echo "Response: $response"
          count=$(echo "$response" | jq -r '.count // 0')
          echo "Pending notifications: $count"
          echo "response=$response" >> $GITHUB_OUTPUT
          echo "count=$count" >> $GITHUB_OUTPUT
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
      
      - name: Process individual notifications
        if: steps.get-pending.outputs.count != '0'
        run: |
          response='${{ steps.get-pending.outputs.response }}'
          notifications=$(echo "$response" | jq -c '.notifications[]')
          
          processed=0
          failed=0
          
          # Use process substitution instead of here-string to avoid subshell
          while IFS= read -r notification; do
            slug=$(echo "$notification" | jq -r '.slug')
            type=$(echo "$notification" | jq -r '.type')
            
            echo "Processing notification for $type: $slug"
            
            if curl -X POST https://personal.emily-cogsdill.workers.dev/api/cron/process-single-notification \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
              -H "Content-Type: application/json" \
              -f \
              --retry 2 \
              --retry-delay 5; then
              echo "✓ Successfully processed notification for $slug"
              processed=$((processed + 1))
            else
              echo "✗ Failed to process notification for $slug"
              failed=$((failed + 1))
            fi
            
            # Small delay between requests to avoid overwhelming the server
            sleep 1
          done < <(echo "$notifications")
          
          echo "Summary: Processed $processed notifications, $failed failed"
          
          if [ $failed -gt 0 ]; then
            exit 1
          fi
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
      
      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.get-pending.outputs.count }}" == "0" ]; then
            echo "No pending notifications to process"
          else
            echo "Completed processing ${{ steps.get-pending.outputs.count }} notifications"
          fi