name: Test Blog Post Notification

on:
  workflow_dispatch:
    inputs:
      blog_slug:
        description: 'Blog post slug (e.g., "20250627-based-and-claude-pilled")'
        required: true
        type: string
      test_email:
        description: 'Test email (optional - if blank, sends to all subscribers)'
        required: false
        type: string

jobs:
  test-notification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get available blog posts
        run: |
          echo "=== AVAILABLE BLOG POSTS ==="
          curl -X GET https://personal.emily-cogsdill.workers.dev/api/admin/check-notifications \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -s | jq -r '.unnotifiedContent[] | select(.type == "blog") | "Slug: \(.slug) - Title: \(.title)"'
          
          echo ""
          echo "You selected: ${{ github.event.inputs.blog_slug }}"
          echo ""
      
      - name: Send test blog notification
        run: |
          echo "=== SENDING TEST BLOG NOTIFICATION ==="
          
          if [ -n "${{ github.event.inputs.test_email }}" ]; then
            echo "Sending to test email: ${{ github.event.inputs.test_email }}"
          else
            echo "Sending to all blog subscribers"
          fi
          
          response=$(curl -X POST https://personal.emily-cogsdill.workers.dev/api/admin/test-blog-notification \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{
              "slug": "${{ github.event.inputs.blog_slug }}",
              "testEmail": "${{ github.event.inputs.test_email }}"
            }' \
            -w "\nHTTP_STATUS:%{http_code}\n" \
            -s)
          
          http_status=$(echo "$response" | tail -n 1 | cut -d: -f2)
          body=$(echo "$response" | head -n -1)
          
          echo "$body" | jq . || echo "$body"
          
          if [ "$http_status" != "200" ]; then
            echo "❌ Failed with HTTP status: $http_status"
            exit 1
          fi
      
      - name: Check notification status
        run: |
          echo ""
          echo "=== CHECKING NOTIFICATION STATUS ==="
          
          # Wait a moment for processing
          sleep 5
          
          curl -X GET https://personal.emily-cogsdill.workers.dev/api/admin/check-notifications \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            -s | jq '{
              summary: .summary,
              recentNotifications: [.recentNotifications[0:3] | .[] | {
                contentId: .contentId,
                status: .status,
                createdAt: .createdAt,
                error: .error
              }]
            }'
      
      - name: Check Resend dashboard
        run: |
          echo ""
          echo "========================================="
          echo "✅ Test notification sent!"
          echo "========================================="
          echo "Check the Resend dashboard for sent emails:"
          echo "https://resend.com/emails"
          echo ""
          echo "Check Cloudflare logs for details:"
          echo "https://dash.cloudflare.com/ > Workers & Pages > personal > Logs"