name: Test Blog Post Email

on:
  workflow_dispatch:
    inputs:
      blog_slug:
        description: 'Blog post slug to test (e.g., "my-blog-post")'
        required: true
        type: string
      test_email:
        description: 'Test email address (optional - if not provided, sends to all subscribers)'
        required: false
        type: string

jobs:
  test-blog-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send test blog notification
        run: |
          echo "🧪 Testing blog notification..."
          echo "Blog slug: ${{ github.event.inputs.blog_slug }}"
          
          if [ -n "${{ github.event.inputs.test_email }}" ]; then
            echo "Test email: ${{ github.event.inputs.test_email }}"
            echo "📧 Sending test email to specific address..."
            
            curl -X POST https://personal.emily-cogsdill.workers.dev/api/admin/test-blog-notification \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
              -H "Content-Type: application/json" \
              -d '{"slug": "${{ github.event.inputs.blog_slug }}", "testEmail": "${{ github.event.inputs.test_email }}"}' \
              -f \
              --retry 3 \
              --retry-delay 10
          else
            echo "📧 Sending to all blog subscribers..."
            
            curl -X POST https://personal.emily-cogsdill.workers.dev/api/admin/test-blog-notification \
              -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
              -H "Content-Type: application/json" \
              -d '{"slug": "${{ github.event.inputs.blog_slug }}"}' \
              -f \
              --retry 3 \
              --retry-delay 10
          fi
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
      
      - name: Check response
        if: failure()
        run: echo "Test blog notification failed"